---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge CI Pipeline

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      loitering-detection_changed: ${{ steps.filter.outputs.loitering-detection }}
      image-based-video-search_changed: ${{ steps.filter.outputs.image-based-video-search }}
      smart-parking_changed: ${{ steps.filter.outputs.smart-parking }}
      pallet-defect-detection_changed: ${{ steps.filter.outputs.pallet-defect-detection }}
      weld-porosity_changed: ${{ steps.filter.outputs.weld-porosity }}
    steps:
      - uses: actions/checkout@v4
      - name: Set paths filter
        id: filter
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        with:
          filters: |
            loitering-detection:
              - 'metro-ai-suite/loitering-detection/docs/**'
            image-based-video-search:
              - 'metro-ai-suite/image-based-video-search/docs/**'
            smart-parking:
              - 'metro-ai-suite/smart-parking/docs/**'
            pallet-defect-detection:
              - 'manufacturing-ai-suite/pallet-defect-detection/docs/**'
            weld-porosity:
              - 'manufacturing-ai-suite/weld-porosity/docs/**'
  build_image-based-video-search:
    if: ${{ (github.event.inputs.target == 'image-based-video-search') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@main
    secrets: inherit
    with:
      docs_directory: metro-ai-suite/image-based-video-search
  build_smart-parking:
    if: ${{ (github.event.inputs.target == 'smart-parking') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@main
    secrets: inherit
    with:
      docs_directory: metro-ai-suite/smart-parking
  build_loitering-detection:
    if: ${{ (github.event.inputs.target == 'loitering-detection') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@main
    secrets: inherit
    with:
      docs_directory: metro-ai-suite/loitering-detection
  build_pallet-defect-detection:
    if: ${{ (github.event.inputs.target == 'pallet-defect-detection') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@main
    secrets: inherit
    with:
      docs_directory: manufacturing-ai-suite/pallet-defect-detection
  build_weld-porosity:
    if: ${{ (github.event.inputs.target == 'weld-porosity') || (github.event.inputs.target == 'all-documentation') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@main
    secrets: inherit
    with:
      docs_directory: manufacturing-ai-suite/weld-porosity
